theme: jekyll-theme-chirpy

lang: en-US

title: meroupatate
tagline: Hoping to share some useful stuff
description: >-
    Hi there, I am Alice and I am a French engineering student at Télécom SudParis.
url: "https://meroupatate.github.io"

paginate: 10

github:
  username: meroupatate
twitter:
  username: meroupatate
social:
  name: Alice ZHEN 
  email: alice.zhen@telecom-sudparis.eu
  links:
    - https://github.com/meroupatate
    - https://twitter.com/meroupatate
    - https://www.linkedin.com/in/alicezhen07

theme_mode: dark
avatar: https://avatars.githubusercontent.com/u/43771848?v=4

disqus:
  comments: true
  shortname: 'meroupatate-github-io'

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order


defaults:
  -
    scope:
      path: ''          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: ''
      type: tabs             # see `site.collections`
    values:
      layout: page
      permalink: /:title/
      dynamic_title: true    # Hide title in mobile screens.

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - '*.gem'
  - '*.gemspec'
  - tools
  - docs
  - README.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - '*.json'

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
